services:
  postgresql:
    container_name: postgresql
    image: postgres:15.4-bullseye
    restart: always

    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_ms_compras
      POSTGRES_USER: dana
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"

    volumes:
      # es buena practica path relativo desde el proyecto ./_data:/var/lib/postgresql
      - ./_data:/var/lib/postgresql/data

networks:
  mired:
    driver: bridge